### ISSUE TITLE
minor build issue 

### ISSUE THREAD

**Issue by mandric** [ushahidi/SMSSync#373]
I'm not very familiar with the latest Java build systems but even after following the instructions in BUILDING.md I was stuck on this error for a bit:

```
$ ./gradlew  --stacktrace clean assemble
Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_OVERRIDE environment variable to "ca015297591386fc28993e8c2f7535f752c91ae4"

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mandric/dev/SMSSync/smssync/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating project ':smssync'.
> Failed to apply plugin [id 'com.android.application']
   > Could not create plugin of type 'AppPlugin'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':smssync'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$1.run(DefaultScriptPluginFactory.java:144)
	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:72)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPlugin
```

Then I tweaked build.gradle and that seemed to fix it:

```
-        classpath 'com.android.tools.build:gradle:2.0.0-beta4'
+        classpath 'com.android.tools.build:gradle:2.0.0-beta7'
```

**Comment by alxndrsn** [comment]
:+1: I needed this change to build via `build.sh`

**Comment by alxndrsn** [comment]
Please merge this change - without it, all PR builds are breaking, e.g. https://travis-ci.org/ushahidi/SMSSync/builds/121709653.
